export interface IEvents {
    AlarmFrames?: string;
    Archived?: string;
    AvgScore?: string;
    Cause?: string;
    DefaultVideo?: string;
    DiskSpace?: string;
    Emailed?: string;
    EndTime?: string;
    Executed?: string;
    FileSystemPath?: string;
    Frames?: string;
    Height?: string;
    Id?: string;
    Length?: string;
    Locked?: boolean;
    MaxScore?: string;
    MaxScoreFrameId?: string;
    Messaged?: string;
    MonitorId?: string;
    Name?: string;
    Notes?: string;
    Orientation?: string;
    SaveJPEGs?: string;
    Scheme?: string;
    SecondaryStorageId?: string;
    StartTime?: string;
    StateId?: string;
    StorageId?: string;
    TotScore?: string;
    Uploaded?: string
}